#!/usr/bin/env ruby

require 'date'
require 'slugify'

POSTS_DIR = '_posts/'

post = ARGV[0]
postFile = post.slugify
date = DateTime.now

File.open(POSTS_DIR + date.strftime("%Y-%m-%d-") + postFile + '.md', 'w') {|f| f.write(
  "---\nlayout: post\nsection-type: post\ntitle: " + post + "\ndate: '" + date.to_s + "'\nauthor: Jørn Ølmheim\ncategory: tech\ntags: [ 'tag1', 'tag2' ]\n---")
}

puts('[+] Created ' + post + ' post')
