#!/usr/bin/env ruby

require 'date'
require 'slugify'

POSTS_DIR = '_posts/'

post = ARGV[0]
postFile = post.slugify

File.open(POSTS_DIR + Date.today.strftime("%Y-%m-%d-") + postFile + '.md', 'w') {|f| f.write(
  "---\nlayout: post\nsection-type: post\ntitle: " + post + "\ncategory: tech\ntags: [ 'tag1', 'tag2' ]\n---")
}

puts('[+] Created ' + post + ' post')
